# Create a virtual environment with all tools installed
# ref: https://hub.docker.com/_/ubuntu
FROM ubuntu:rolling AS env

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install system build dependencies
RUN apt-get update -qq \
&& apt-get install -yq git wget curl libssl-dev build-essential libglpk-dev \
&& apt-get install -yq python3-dev python3-pip \
&& apt-get install -yq default-jdk \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
# Install Bazel 8.0.1 (pinned for rules_go/rules_java compatibility)
RUN curl -fsSL https://github.com/bazelbuild/bazel/releases/download/8.0.1/bazel-8.0.1-linux-x86_64 -o /usr/local/bin/bazel \
    && chmod +x /usr/local/bin/bazel

FROM env AS devel
WORKDIR /home/project
COPY . .

FROM devel AS build
RUN bazel version
RUN bazel build --curses=no --cxxopt=-std=c++20 --copt=-Wno-sign-compare --//ortools/linear_solver:with_glpk=true //ortools/math_opt/tools:mathopt_solve

FROM ubuntu:rolling as package
COPY --from=build /home/project/bazel-bin/ortools/math_opt/tools/mathopt_solve /
RUN mkdir /testsuite
COPY ortools/linear_solver/testdata/maximization.mps /testsuite
